version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  broker:
    image: redis
    ports:
      - '6379:6379'

  worker:
    build: ./market
    entrypoint: /home/trader/app/entrypoint_worker.sh
    depends_on:
      - broker
      - app

  app:
    build: ./market
    entrypoint: /home/trader/app/entrypoint.sh
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  client:
    build: ./coin-market
    ports:
      - 80:80
    depends_on:
      - app
      - worker

volumes:
  postgres_data: