# Generated by Django 4.1 on 2023-09-16 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Coin',
                'verbose_name_plural': 'Coins',
                'db_table': 'coins_coin',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=16, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'coin_currency',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('market_cap', models.FloatField(verbose_name='Market Cap')),
                ('total_volume', models.FloatField(verbose_name='Total Volume')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.coin', verbose_name='Coin')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coins.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'History',
                'db_table': 'coins_history',
                'unique_together': {('coin', 'timestamp')},
            },
        )
    ]
